1. Write a Python Program to Add Two Matrices?

In [1]:
rows = int(input("Enter the Number of rows : " ))
column = int(input("Enter the Number of Columns: "))

print("Enter the elements of First Matrix:")
matrix_a= [[int(input()) for i in range(column)] for i in range(rows)]
print("First Matrix is: ")
for n in matrix_a:
    print(n)

print("Enter the elements of Second Matrix:")
matrix_b= [[int(input()) for i in range(column)] for i in range(rows)]
for n in matrix_b:
    print(n)
    
result=[[0 for i in range(column)] for i in range(rows)]

for i in range(rows):
    for j in range(column):
        result[i][j] = matrix_a[i][j]+matrix_b[i][j]

print("The Sum of Above two Matrices is : ")
for r in result:
    print(r)

Enter the Number of rows : 2
Enter the Number of Columns: 2
Enter the elements of First Matrix:
12
23
34
45
First Matrix is: 
[12, 23]
[34, 45]
Enter the elements of Second Matrix:
56
34
25
16
[56, 34]
[25, 16]
The Sum of Above two Matrices is : 
[68, 57]
[59, 61]


2. Write a Python Program to Multiply Two Matrices?

In [5]:
A = [[12, 7, 3],
    [4, 5, 6],
    [7, 8, 9]]
 
B = [[5, 8, 1, 2],
    [6, 7, 3, 0],
    [4, 5, 9, 1]]
     
result = [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]
 
for i in range(len(A)):
 
    for j in range(len(B[0])):
 
        for k in range(len(B)):
            result[i][j] += A[i][k] * B[k][j]
 
for r in result:
    print(r)

[114, 160, 60, 27]
[74, 97, 73, 14]
[119, 157, 112, 23]


3. Write a Python Program to Transpose a Matrix?

In [6]:
import numpy as np

arr1 = np.array([[1, 2, 3], [4, 5, 6]])

print(f'Original Array:\n{arr1}')

arr1_transpose = arr1.transpose()

print(f'Transposed Array:\n{arr1_transpose}')

Original Array:
[[1 2 3]
 [4 5 6]]
Transposed Array:
[[1 4]
 [2 5]
 [3 6]]


4. Write a Python Program to Sort Words in Alphabetic Order?

In [9]:
my_str = input("Enter a string: ")

words = [word.lower() for word in my_str.split()]

words.sort()

print("The sorted words are:")
for word in words:
   print(word)

Enter a string: Hello this Is an Example With cased letters
The sorted words are:
an
cased
example
hello
is
letters
this
with


5. Write a Python Program to Remove Punctuation From a String?

In [10]:
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''

my_str = input("Enter a string: ")

no_punct = ""
for char in my_str:
   if char not in punctuations:
       no_punct = no_punct + char

print(no_punct)


Enter a string: "Hello!!!, he said ---and went."
Hello he said and went
